services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql_01
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"]
      interval: 5s
      timeout: 20s
      retries: 30

  init:
    container_name: mysql-init
    build:
      context: ./init
    volumes:
      - /tmp/mysql:/usr/lib/mysql
      - /tmp/shared:/usr/lib/shared
    env_file:
      - .env 
    environment:
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
   
    depends_on:
      db:
        condition: service_healthy
  
  django:
    container_name: django-container
    build:
      context: .  # The directory where your Dockerfile is located
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_HOST=${SQL_HOST}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_PORT=${SQL_PORT}
    ports:
      - 8000:8000
