services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql_01
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"]
      interval: 5s
      timeout: 20s
      retries: 30
  
  django:
    container_name: django-container
    image: django:latest # or specify a custom Dockerfile if you have one
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app/Movie_project
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${SQL_USER}:${SQL_PASSWORD}@db:3306/${SQL_DATABASE}
    ports:
      - 8000:8000
